### ISSUE TITLE
rendering error

### ISSUE THREAD

**Issue by vivalaakam** [shakacode/react-webpack-rails-tutorial#111] opened 2015-10-08 08:45 UTC
I get lastest  version of repo compile all run on my pc and when i try to get main page
Exception in rendering!

Message: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (<eval>:27969:16)
    at traverseAllChildrenImpl (<eval>:40373:230)
    at traverseAllChildrenImpl (<eval>:40329:24)
    at traverseAllChildren (<eval>:40401:11)
    at mapIntoWithKeyPrefixInternal (<eval>:40153:4)
    at Object.mapChildren [as map] (<eval>:40173:4)
    at Object.mapValidComponents [as map] (<eval>:47020:39)
    at renderUl (<eval>:47627:49)
    at render (<eval>:47605:15)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (<eval>:11703:35)

**Comment by vivalaakam** [comment] 2015-10-08 09:53
problem was in npm module react-bootstrap@0.25.2

**Comment by dustingetz** [comment] 2015-10-08 15:39
Can you post more details? I think everyone who does a fresh clone today is broken

**Comment by vivalaakam** [comment] 2015-10-08 16:15
this error was in react-bootstrap@0.25.2 , version 0.25.1 was working normally. Also test on 0.26.4 working too

**Comment by dylangrafmyre** [comment] 2015-10-08 16:16
@vivalaakam Thanks, I am testing 0.26.4 right now and will fix.

**Comment by dylangrafmyre** [comment] 2015-10-08 16:37
@vivalaakam Thanks again. I confirmed this issue by cloning the repo. Upgrading react-bootstrap to @0.26.4 resolved the render error.

**Comment by dustingetz** [comment] 2015-10-08 16:59
From a fresh clone, and i verified react-bootstrap 0.26.4 in npm_modules,

`Uncaught Error: Invariant Violation: Objects are not valid as a React child (found: object with keys {type, key, ref, _owner, _context, _store}). It looks like you're using an element created by a different version of React. Make sure to use only one copy of React.`

Is this a different error than what you saw?

**Comment by dustingetz** [comment] 2015-10-08 17:00
I am at `2b7f67f Merge pull request #112 from shakacode/render-error#111`, fresh clone.

**Comment by dylangrafmyre** [comment] 2015-10-08 17:01
@dustingetz Yes, this is different.

**Comment by dylangrafmyre** [comment] 2015-10-08 17:22
@dustingetz I actually got the initial reported error again. However, `rm -rf client/node_modules` and `rm -rf client/npm-shrinkwrap.json` followed by `npm install` and `cd client && npm shrinkwrap` fixed my error.

`foreman start -f Procfile.dev` shows everything is loaded good and localhost:4000 renders now errors.

Can you try on your end. I will open this issue back up and keep investigating the issue. Thanks!

**Comment by dylangrafmyre** [comment] 2015-10-08 17:23
This still needs to be investigate further.

**Comment by dustingetz** [comment] 2015-10-08 17:24
What was the initial reported error?

**Comment by dylangrafmyre** [comment] 2015-10-08 17:24
The one by @vivalaakam at the top of this issue.

**Comment by dustingetz** [comment] 2015-10-08 17:27
The `Uncaught Error: Invariant Violation` error came out of the js console on :3000. I get the same or very similar error on :4000. Trying again now, sorry, I already rm-rfed everything and waiting on npm.

**Comment by dustingetz** [comment] 2015-10-08 17:39
Deleting npm-shrinkwrap and installing again fixed the problem.

**Comment by dylangrafmyre** [comment] 2015-10-08 17:47
@dustingetz Thanks. We were also able to replicate your error.

**Comment by dylangrafmyre** [comment] 2015-10-08 19:33
@dustingetz We updated all npm packages and cannot reproduce this issue anymore on fresh clone of the repo. Please let us know if you have any further issues. Thanks!

**Comment by dylangrafmyre** [comment] 2015-10-08 19:35
Fixed by PR #113

**Closed by dylangrafmyre** 2015-10-08 19:35 UTC
