### ISSUE TITLE
client/webpack.client.rails.hot.config.js: importLoaders 1 => 0?

### ISSUE THREAD

**Issue by vsai** [shakacode/react-webpack-rails-tutorial#391] opened 2017-05-16 08:43 UTC
In 001a3ae5, it looks like the importLoaders value for 'css-loader' was changed from 1 to 0.
Is this expected? Don't see why this should've changed.

**Comment by justin808** [comment] 2017-06-04 00:24
Hey -- maybe! can use some help on getting hot reloading, etc. working!

**Comment by vsai** [comment] 2017-06-08 08:35
Hey @justin808 I've taken a look at it but that didn't seem to fix it. I'm looking to see how to get webpack hot reloading working, but I'm not too experienced with node+webpack configs and had a few questions if you could help me out?

(1)
localhost:3500/webpack-dev-server (lists the files as so:)
```
app-bundle.js
app-bundle (magic html for app-bundle.js) (webpack-dev-server)
vendor-bundle-1de0b2efad7346d3638c.js
vendor-bundle-1de0b2efad7346d3638c (magic html for vendor-bundle-1de0b2efad7346d3638c.js) (webpack-dev-server)
manifest.json
```

clicking app-bundle.js / vender-bundle-[hash].js / manifest.json correctly displays the file.
clicking app-bundle / vendor-bundle-[hash] says that there is an error proxying through http://lvh.me:3500
Could this be an issue with webpack-dev-server itself? Maybe the proxy is not defined properly? Maybe contentBase is not defined correctly?
FWIW, the build output includes:
```
Using a URL as contentBase is deprecated and will be removed in the next major version. Please use the proxy option instead.
proxy: {
       "*": "<your current contentBase configuration>"
}
```

(2)
In webpack.client.rails.hot.config.js,
```
output: {
  filename: '[name].js',
  path: webpackOutputPath,
},
```
doesn't include
```
publicPath: `/${webpackPublicOutputDir}/`
```
Is this needed? A public path was defined in the old configuration.

(3)
```
<%= stylesheet_pack_tag('vendor-bundle', media: 'all', 'data-turbolinks-track': true) %>
<%= stylesheet_pack_tag('app-bundle', media: 'all', 'data-turbolinks-track': true) %>
```
In hot reloading, this generates:
```
<link rel="stylesheet" media="all" href="/webpack/development/.css" data-turbolinks-track="true">
<link rel="stylesheet" media="all" href="/webpack/development/.css" data-turbolinks-track="true">
```
Without any actual css filename. Is this expected not to generate the correct links for css files? I'm guessing so because we don't hot reload css files onto the page. But just wanted to confirm.

(4)
```
<script src="/webpack/development/vendor-bundle-24a27ea485f3069d2d99.js" data-turbolinks-track="true"></script>
<script src="/webpack/development/app-bundle.js" data-turbolinks-track="true"></script>
```
These are returning 404s too. But I think that's part of the hot-reloading problem not finding the correct files, right?

**Comment by szyablitsky** [comment] 2017-06-09 02:33
@vsai just remove `rails-static-client-assets` entry from `Procfile.dev`
You should have either hot assets or static ones in procfile because they both write in `manifest.json` and write different things. One process overwrites the other's version of `manifest.json`

**Comment by justin808** [comment] 2017-06-09 21:19
@szyablitsky should this one be left open? Any todo's from this one? Docs? Code?

**Comment by szyablitsky** [comment] 2017-06-13 05:55
@justin808 I do not know what is your preferred config for development.
For me, after trying react-on-rails 8 with webpacker_lite I decided to keep only two Procfiles: `Procfile.dev` (without static client, with hot reolading) and `Procfile.static` (with static client, without hot reloading).

**Comment by justin808** [comment] 2017-06-13 06:17
@szyablitsky if you can update this repo the way we did for https://github.com/shakacode/react_on_rails spec/dummy, that would be amazing!

See: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/hot-reloading-rails-development.md

**Comment by justin808** [comment] 2017-07-16 07:21
@vsai @szyablitsky What's next on this task?

**Comment by szyablitsky** [comment] 2017-07-16 08:46
@justin808 right now we are on tight schedule to the first beta of our project, so I can't help you with documentation fixes in near future.
I think you should close this issue and open another clearly named about patching hot reloading documentation to the current state.

**Comment by justin808** [comment] 2018-08-09 18:08
Closing b/c the issue is stale.

**Closed** 2018-08-09 18:08 UTC
Labels: question
